version: '3.5'
services:
  apiserver:
    build:
      context: apiserver
    volumes:
      - "./data:/opt/data"
    ports:
      - "3000:3000"
    restart: always
    ulimits:
      nofile:
        soft: 512
        hard: 1024
    healthcheck:
      test: curl --fail -s http://localhost:3000/ || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
    privileged: true
    environment:
      - DISABLE_ACCESS_COUNT=1
      - SCOPE_OUT_DEST=udp://${CRIBL_STATSD}
  redis:
    build:
      context: redis
    ports:
      - "6379:6379"
    environment:
      - SCOPE_OUT_DEST=udp://${CRIBL_STATSD}

